#!/usr/bin/env bash

if ! [[ $1 == "rgb" || $1 == "rgba" || $1 == "frgb" || $1 == "frgba" || $1 == "hex" || $1 == "hexa" || $1 == "HEX" || $1 == "HEXA" ]]; then
    echo "First argument must not be empty"
    echo "Possible values for the first argument are 'rgb', 'rgba', 'hex', 'hexa', 'HEX', 'HEXA'"
    exit 1
fi

maim /tmp/color-picker-full-screenshot.png --hidecursor
{
    SLOP=$(slop -r boxzoom -t 0 -f "%x %y %w %h")
} || exit 1
read -r X Y _ _ <<< "$SLOP"

FORMAT=""
PARSER=""
if [[ $1 == "rgb" ]]; then
    FORMAT="%[pixel:p{$X,$Y}]"
    PARSER='s/srgba(\(.*\),\(.*\),\(.*\),.*)/rgb(\1,\2,\3)/'
elif [[ $1 == "rgba" ]]; then
    FORMAT="%[pixel:p{$X,$Y}]"
    PARSER='s/srgba(\(.*\),\(.*\),\(.*\),\(.*\))/rgba(\1,\2,\3,\4)/'
elif [[ $1 == "frgb" ]];then
    FORMAT="%[fx:p{$X,$Y}.r],%[fx:p{$X,$Y}.g],%[fx:p{$X,$Y}.b]"
    PARSER='s/\(.*\)/rgb(\1)/'
elif [[ $1 == "frgba" ]]; then
    FORMAT="%[fx:p{$X,$Y}.r],%[fx:p{$X,$Y}.g],%[fx:p{$X,$Y}.b],%[fx:p{$X,$Y}.a]"
    PARSER='s/\(.*\)/rgb(\1)/'
elif [[ $1 == "hex" ]]; then
    FORMAT="%[hex:p{$X,$Y}]"
    PARSER='s/\(......\)../#\L\1/'
elif [[ $1 == "hexa" ]]; then
    FORMAT="%[hex:p{$X,$Y}]"
    PARSER='s/\(........\)/#\L\1/'
elif [[ $1 == "HEX" ]]; then
    FORMAT="%[hex:u.p{$X,$Y}]"
    PARSER='s/\(......\)../#\1/'
elif [[ $1 == "HEXA" ]]; then
    FORMAT="%[hex:u.p{$X,$Y}]"
    PARSER='s/\(........\)/#\1/'
else
    echo "unexpected error"
    exit 2
fi

# maim /tmp/color-picker-full-screenshot.png --hidecursor
# SLOP=$(slop -r boxzoom -t 0 -f "%x %y %w %h")
# read -r X Y W H <<< $SLOP
# maim -g $(slop -r boxzoom -t 0) --hidecursor \
#     | convert - -format $FORMAT info:- \
#     | sed $PARSER \
#     | xclip -selection clipboard


convert /tmp/color-picker-full-screenshot.png -format "$FORMAT" info:- \
    | sed "$PARSER" \
    | xclip -selection clipboard

