#!/usr/bin/env bash

if [[ $1 == "auto" ]]
then
    xrandr --output eDP-1 --mode 1920x1080
    xrandr --output HDMI-1 --off
elif [[ $1 == "split" ]]
then
    xrandr --output eDP-1 --mode 1920x1080
    xrandr --output HDMI-1 --auto
    xrandr --output HDMI-1 --right-of eDP-1
elif [[ $1 == "duplicate" ]]
then
    xrandr --output eDP-1 --mode 1920x1080
    xrandr --output HDMI-1 --mode 1920x1080 || xrandr --output HDMI-1 --auto
    xrandr --output HDMI-1 --same-as eDP-1
elif [[ $1 == "follow" ]]
then
    xrandr --output eDP-1 --off
    xrandr --output HDMI-1 --auto
fi

systemctl --user restart random-changing-background.service
