#!/usr/bin/env bash

# Possible brightness values:
# 255, 128,  64,  32,  16,   0

CURR_VAL=$(xrandr --verbose | grep -oP "Brightness: \K.*")
if [[ $CURR_VAL != "1.0" ]] && [[ $CURR_VAL != "0.75" ]] && [[ $CURR_VAL != "0.50" ]] && [[ $CURR_VAL != "0.25" ]]
then
    xrandr --output eDP-1 --brightness 1
    exit 0
fi

re='^[+-]$'
if ! [[ $1 =~ $re ]]; then
	echo "error: first parameter must be either '+' or '-'" >&2; exit 1
fi

if [[ $1 == '+' ]]; then
    if [[ $CURR_VAL == "0.25" ]]
    then
        xrandr --output eDP-1 --brightness 0.5
    elif [[ $CURR_VAL == "0.50" ]]
    then
        xrandr --output eDP-1 --brightness 0.75
    else
        xrandr --output eDP-1 --brightness 1
    fi
else
    if [[ $CURR_VAL == "1.0" ]]
    then
        xrandr --output eDP-1 --brightness 0.75
    elif [[ $CURR_VAL == "0.75" ]]
    then
        xrandr --output eDP-1 --brightness 0.5
    else
        xrandr --output eDP-1 --brightness 0.25
    fi
fi

# DEVICE=$(ls /sys/class/backlight | head -1)
# MAX_VAL=$(cat /sys/class/backlight/$DEVICE/max_brightness)
# if [[ $MAX_VAL -ne 255 ]]; then
# 	echo "error: device with weird max brightness ($MAX_VAL instead of 255)" >&2; exit 1
# fi
#
# CURR_VAL=$(cat /sys/class/backlight/$DEVICE/brightness)
# NEW_VAL=$CURR_VAL
# if [[ $1 == '+' ]]; then
# 	if [[ $CURR_VAL -ge 128 ]]; then
# 		NEW_VAL=255
# 	elif [[ $CURR_VAL -ge 64 ]]; then
# 		NEW_VAL=128
# 	elif [[ $CURR_VAL -ge 32 ]]; then
# 		NEW_VAL=64
# 	elif [[ $CURR_VAL -ge 16 ]]; then
# 		NEW_VAL=32
# 	else
# 		NEW_VAL=16
# 	fi
# else
# 	if [[ $CURR_VAL -le 16 ]]; then
# 		NEW_VAL=0
# 	elif [[ $CURR_VAL -le 32 ]]; then
# 		NEW_VAL=16
# 	elif [[ $CURR_VAL -le 64 ]]; then
# 		NEW_VAL=32
# 	elif [[ $CURR_VAL -le 128 ]]; then
# 		NEW_VAL=64
# 	else
# 		NEW_VAL=128
# 	fi
# fi
#
# echo $NEW_VAL > /sys/class/backlight/$DEVICE/brightness

