#!/usr/bin/env bash

DIR="$(xdg-user-dir PICTURES)/Screenshots"
mkdir -p "$DIR"

TS=$(date +%F_%T)

maim --format="png" --hidecursor --select | convert - -resize '600x800<' "$DIR/$TS.png"

xclip -selection clipboard -t image/png <"$DIR/$TS.png"
