#!/usr/bin/env bash

# This value will be changed to 0 upon value interpolation by NixOS at compile
STOP_EXECUTION_BEFORE_INTERPOLATION=1

if [[ $STOP_EXECUTION_BEFORE_INTERPOLATION -eq 1 ]]; then
	echo "!!! DO NOT RUN THIS SCRIPT DIRECTLY !!!"
	echo ""
	echo "This script is not meant to be run directly, as it uses some value interpolation"
	echo "performed by NixOS at compile time."
	echo ""
	echo "If you want to run this script without NixOS, copy it and take some time to"
	echo "make the necessary changes"
	echo ""
	echo "Values meant to be interpolated use the <nix-interpolate:name> nomenclature and usually have"
	echo "the intended interpolated value next to them as a comment"

	exit 1
fi

PRIMARY="<nix-interpolate:primary-monitor-output>" # "eDP-1"

CURR_VAL=$(xrandr --verbose | grep -oP "Brightness: \K.*")
if [[ $CURR_VAL != "1.0" ]] && [[ $CURR_VAL != "0.75" ]] && [[ $CURR_VAL != "0.50" ]] && [[ $CURR_VAL != "0.25" ]]; then
	xrandr --output "$PRIMARY" --brightness 1
	exit 0
fi

re='^[+-]$'
if ! [[ $1 =~ $re ]]; then
	echo "error: first parameter must be either '+' or '-'" >&2
	exit 1
fi

if [[ $1 == '+' ]]; then
	if [[ $CURR_VAL == "0.25" ]]; then
		xrandr --output "$PRIMARY" --brightness 0.5
	elif [[ $CURR_VAL == "0.50" ]]; then
		xrandr --output "$PRIMARY" --brightness 0.75
	else
		xrandr --output "$PRIMARY" --brightness 1
	fi
else
	if [[ $CURR_VAL == "1.0" ]]; then
		xrandr --output "$PRIMARY" --brightness 0.75
	elif [[ $CURR_VAL == "0.75" ]]; then
		xrandr --output "$PRIMARY" --brightness 0.5
	else
		xrandr --output "$PRIMARY" --brightness 0.25
	fi
fi
