{ lib, pkgs, config, ... }:

with lib; {
    options.my.options.generic = {
        enable = mkEnableOption "";
    };

    config = let
        keep-images = pkgs.callPackage ./keep-images {};
        batch-rename = pkgs.writeShellApplication {
            name = "batch-rename";
            runtimeInputs = with pkgs; [
                gnused
            ];
            text = builtins.readFile ./batch-rename;
        };
        poke2term = pkgs.writers.writePython3Bin "poke2term" {
            libraries = [
                pkgs.python3Packages.requests
                pkgs.python3Packages.pillow
            ];
            flakeIgnore = [
                "E265"  # Ignore error generated by shebang (block comment should start with '# ')
                "E501"  # Ignore 'line too long' errors
            ];
        } (builtins.readFile ./poke2term);
    in mkIf config.my.options.generic.enable {
        environment.systemPackages = [
            keep-images
            batch-rename
            poke2term
        ];
    };
}
