# --- SSH --- #
## Export
[[exports.shared]]
source="/home/baldo/.ssh"
endpoint="ssh/$profile"
files = ["id_ed25519", "id_ed25519.pub"]

## Import
[[imports.shared]]
source="ssh/$profile"
endpoint="/home/baldo/.ssh"
files = ["id_ed25519", "id_ed25519.pub"]
symlinks_to="/root/.ssh"

[[imports.umbreon]]
source="ssh/latias"
endpoint="/secrets/ssh-pub-keys/latias"
files = ["id_ed25519.pub"]

[[imports.kyogre]]
source="ssh/latias"
endpoint="/secrets/ssh-pub-keys/latias"
files = ["id_ed25519.pub"]
# --- ---#

# --- Wireguard --- #
## Export
[[exports.latias]]
source="/secrets/wireguard/latias"
endpoint="wireguard/latias"
files = ["wg-vps.private", "wg-vps.public", "wg-proton.private", "wg-proton.public"]

[[exports.latias]]
source="/secrets/wireguard/proton"
endpoint="wireguard/proton"
files = ["wg0.public"]

## Import
[[imports.latias]]
source="wireguard/latias"
endpoint="/secrets/wireguard/latias"
files = ["wg-vps.private", "wg-vps.public", "wg-proton.private", "wg-proton.public"]

[[imports.latias]]
source="wireguard/proton"
endpoint="/secrets/wireguard/latias"
files = ["wg-vps.private", "wg-vps.public", "wg-proton.private", "wg-proton.public"]
# --- --- #
