[secrets]
latias = [
  "ssh/latias/id_ed25519",
  "ssh/latias/id_ed25519.pub",
  "wg/latias/wg-home.public",
  "wg/latias/wg-home.private",
  "wg/latias/wg-vps.public",
  "wg/latias/wg-vps.private",
  "wg/latias/wg-proton.public",
  "wg/latias/wg-proton.private",
  "wg/proton/wg0.public"
]
umbreon = [
  "ssh/umbreon/id_ed25519",
  "ssh/umbreon/id_ed25519.pub",
  "wg/umbreon/wg0.private",
  "wg/umbreon/wg0.public"
]
altaria = [
  "wg/altaria/wg0.private",
  "wg/altaria/wg0.public"
]

[additional_imports]
latias = [
  "wg/altaria/wg0.public",
  "wg/umbreon/wg0.public"
]
umbreon = [
  "ssh/latias/id_ed25519.pub",
  "wg/latias/wg-home.public",
]
altaria = [
  "ssh/latias/id_ed25519.pub",
  "wg/latias/wg-vps.public"
]
