#!/usr/bin/env bash

output_info() {
    {
        VOLUME=$(get-volume) &&
            MUTE=$(get-mute) &&
            SINK=$(get-sink)
    } || {
        VOLUME="100"
        MUTE="muted"
        SINK="{ \"name\": \"Main\", \"icon\": \"unknown\" }"
    }

    echo "{ \"volume\": $VOLUME, \"mute\": \"$MUTE\", \"sink\": $SINK }"
}

output_info_on_newline() {
    while read -r _UNUSED_LINE; do
        output_info
    done
}

# Output volume once when run for the initial value
output_info

# Listen to sink changes and output volume every sink update
pactl subscribe | stdbuf -o0 grep --line-buffered "sink" | output_info_on_newline
