#!/usr/bin/env bash

output_info_on_newline() {
    while read -r XMONAD_INFO; do
        # shellcheck disable=SC2001
        CURRENT_WS=$(sed 's/.*"\(.*\)"/\1/; s/.*> //; s/ <.*//' <<<"$XMONAD_INFO")
        get-workspaces-info "$CURRENT_WS"
    done
}

# Listen to sink changes and output volume every sink update
xprop -spy -root _XMONAD_LOG | output_info_on_newline
