#!/usr/bin/env bash

LAST_WARN_AT=100

while true
do
    BATTERY_LEVEL=$(acpi -b | grep -oP '[0-9]+(?=%)')

    if [[ $BATTERY_LEVEL -le 20 ]]
    then
        if [[ $LAST_WARN_AT -gt 20 ]]
        then
            notify-send -u critical "Battery below 20%!!!"
        fi
        LAST_WARN_AT=20

    elif [[ $BATTERY_LEVEL -le 30 ]]
    then
        if [[ $LAST_WARN_AT -gt 30 ]]
        then
            notify-send -u critical "Battery below 30%"
        fi
        LAST_WARN_AT=30

    else
        LAST_WARN_AT=100
    fi

    sleep 5 # seconds
done
